// Generated by Wrangler by running `wrangler types`

interface Env {
	PRODUCTION: string;
	DO: DurableObjectNamespace<import("./worker/index").DurableObject>;
	RENDER_COORDINATOR: DurableObjectNamespace<import("./worker/index").RenderCoordinator>;
	BROWSER: Fetcher;
	ASSETS: Fetcher;
}
